# build only master and PR to master
if: branch = master
language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - '~/.cache'
install:
  - yarn
script:
  # - yarn test:e2e:ci
  - yarn build
  - bash deploy.sh
  - node notify.js
