# build only master and PR to master
if: branch = master
language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - '~/.cache'
install:
  - yarn
script:
  - yarn test:e2e:ci
  - |
    if [ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]; then 
      yarn deploy > netlify.log;
    else
      yarn deploy:preview > netlify.log;
    fi
  - node build.js
