[build.processing]
  skip_processing = true

[[redirects]]
  from = "https://malcolmkee.netlify.app/*"
  to = "https://malcolmkee.com/:splat"
  status = 301

[[redirects]]
  from = "/spa/*"
  to = "/spa/index.html"
  status = 200
  force = true

[dev]
  command = "pnpm run dev"
  targetPort = 8989