// This file is auto-generated by @hey-api/openapi-ts

import {
  http,
  type HttpHandler,
  HttpResponse,
  type HttpResponseResolver,
  type RequestHandlerOptions as RequestHandlerOptions2,
} from 'msw';

import type {
  AddCartItemData,
  AddCartItemResponses,
  AddProductCommentData,
  AddProductCommentResponses,
  ClientOptions,
  CreateChatRoomData,
  CreateChatRoomResponses,
  CreateJobApplicationData,
  CreateJobApplicationResponses,
  CreateJobData,
  CreateJobResponses,
  CreateListingData,
  CreateListingResponses,
  CreateMarketingDataData,
  CreateMarketingDataResponses,
  CreateMovieCommentData,
  CreateMovieCommentResponses,
  CreateProductData,
  CreateProductResponses,
  CreateUserData,
  CreateUserResponses,
  DeleteJobApplicationResponses,
  DeleteJobResponses,
  DeleteListingResponses,
  DeleteMovieCommentResponses,
  DeleteProductResponses,
  DeleteUserResponses,
  GetChatRoomResponses,
  GetGlobalChatRoomResponses,
  GetJobResponses,
  GetJobsResponses,
  GetListingResponses,
  GetMarketingDataByIdResponses,
  GetMarketingDataByTypeResponses,
  GetMovieResponses,
  GetMoviesResponses,
  GetProductResponses,
  GetProductsResponses,
  GetProfileResponses,
  GetUserResponses,
  JobChatRoomResponses,
  ListCartItemsResponses,
  ListJobApplicationsResponses,
  ListJobsResponses,
  ListJoinedChatRoomsResponses,
  ListListingsResponses,
  ListMovieCommentsResponses,
  ListMoviesResponses,
  ListProductsResponses,
  ListUsersResponses,
  LoginData,
  LoginResponses,
  RegisterData,
  RegisterResponses,
  RemoveCartItemResponses,
  RemoveMarketingDataResponses,
  SendChatMessageData,
  SendChatMessageResponses,
  UpdateChatMessageData,
  UpdateChatMessageResponses,
  UpdateJobData,
  UpdateJobResponses,
  UpdateListingData,
  UpdateListingResponses,
  UpdateProductData,
  UpdateProductResponses,
  UpdateUserData,
  UpdateUserResponses,
  UploadFileData,
  UploadFileResponses,
} from './types.gen';

export type RequestHandlerOptions = RequestHandlerOptions2 & {
  baseUrl?: ClientOptions['baseUrl'];
  responseFallback?: 'error' | 'passthrough';
};

export type HandleGetProductsResponse = {
  body: GetProductsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /product` operation.
 */
export function handleGetProducts(
  response?: HandleGetProductsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/product`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateProductResponse = {
  body: CreateProductResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /product` operation.
 */
export function handleCreateProduct(
  response?: HandleCreateProductResponse | HttpResponseResolver<never, CreateProductData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateProductData['body']>(
    `${options?.baseUrl ?? '*'}/product`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListProductsResponse = {
  body: ListProductsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /product/list` operation.
 */
export function handleListProducts(
  response?: HandleListProductsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/product/list`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleDeleteProductResponse = {
  body: DeleteProductResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /product/{id}` operation.
 */
export function handleDeleteProduct(
  response?:
    | HandleDeleteProductResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/product/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetProductResponse = {
  body: GetProductResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /product/{id}` operation.
 */
export function handleGetProduct(
  response?:
    | HandleGetProductResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/product/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleUpdateProductResponse = {
  body: UpdateProductResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /product/{id}` operation.
 */
export function handleUpdateProduct(
  response?:
    | HandleUpdateProductResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        UpdateProductData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.put<
    {
      id: string;
    },
    UpdateProductData['body']
  >(
    `${options?.baseUrl ?? '*'}/product/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleAddProductCommentResponse = {
  body: AddProductCommentResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /product/comment/{id}` operation.
 */
export function handleAddProductComment(
  response?:
    | HandleAddProductCommentResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        AddProductCommentData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<
    {
      id: string;
    },
    AddProductCommentData['body']
  >(
    `${options?.baseUrl ?? '*'}/product/comment/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetJobsResponse = {
  body: GetJobsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /job` operation.
 */
export function handleGetJobs(
  response?: HandleGetJobsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/job`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateJobResponse = {
  body: CreateJobResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /job` operation.
 */
export function handleCreateJob(
  response?: HandleCreateJobResponse | HttpResponseResolver<never, CreateJobData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateJobData['body']>(
    `${options?.baseUrl ?? '*'}/job`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListJobsResponse = {
  body: ListJobsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /job/list` operation.
 */
export function handleListJobs(
  response?: HandleListJobsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/job/list`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleDeleteJobResponse = {
  body: DeleteJobResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /job/{id}` operation.
 */
export function handleDeleteJob(
  response?:
    | HandleDeleteJobResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/job/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetJobResponse = {
  body: GetJobResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /job/{id}` operation.
 */
export function handleGetJob(
  response?:
    | HandleGetJobResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/job/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleUpdateJobResponse = {
  body: UpdateJobResponses[200];
  status?: 200;
};

/**
 * Handler for the `PATCH /job/{id}` operation.
 */
export function handleUpdateJob(
  response?:
    | HandleUpdateJobResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        UpdateJobData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.patch<
    {
      id: string;
    },
    UpdateJobData['body']
  >(
    `${options?.baseUrl ?? '*'}/job/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListJobApplicationsResponse = {
  body: ListJobApplicationsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /job-application` operation.
 */
export function handleListJobApplications(
  response?: HandleListJobApplicationsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/job-application`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateJobApplicationResponse = {
  body: CreateJobApplicationResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /job-application` operation.
 */
export function handleCreateJobApplication(
  response?:
    | HandleCreateJobApplicationResponse
    | HttpResponseResolver<never, CreateJobApplicationData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateJobApplicationData['body']>(
    `${options?.baseUrl ?? '*'}/job-application`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleDeleteJobApplicationResponse = {
  body: DeleteJobApplicationResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /job-application/{id}` operation.
 */
export function handleDeleteJobApplication(
  response?:
    | HandleDeleteJobApplicationResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/job-application/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetMarketingDataByTypeResponse = {
  body: GetMarketingDataByTypeResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /marketing/type/{type}` operation.
 */
export function handleGetMarketingDataByType(
  response?:
    | HandleGetMarketingDataByTypeResponse
    | HttpResponseResolver<
        {
          type: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      type: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/marketing/type/:type`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateMarketingDataResponse = {
  body: CreateMarketingDataResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /marketing` operation.
 */
export function handleCreateMarketingData(
  response?:
    | HandleCreateMarketingDataResponse
    | HttpResponseResolver<never, CreateMarketingDataData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateMarketingDataData['body']>(
    `${options?.baseUrl ?? '*'}/marketing`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleRemoveMarketingDataResponse = {
  body: RemoveMarketingDataResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /marketing/record/{id}` operation.
 */
export function handleRemoveMarketingData(
  response?:
    | HandleRemoveMarketingDataResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/marketing/record/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetMarketingDataByIdResponse = {
  body: GetMarketingDataByIdResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /marketing/record/{id}` operation.
 */
export function handleGetMarketingDataById(
  response?:
    | HandleGetMarketingDataByIdResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/marketing/record/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleUploadFileResponse = {
  body: UploadFileResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /file/upload` operation.
 */
export function handleUploadFile(
  response?: HandleUploadFileResponse | HttpResponseResolver<never, UploadFileData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, UploadFileData['body']>(
    `${options?.baseUrl ?? '*'}/file/upload`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleRegisterResponse = {
  body: RegisterResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /register` operation.
 */
export function handleRegister(
  response?: HandleRegisterResponse | HttpResponseResolver<never, RegisterData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, RegisterData['body']>(
    `${options?.baseUrl ?? '*'}/register`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleLoginResponse = {
  body: LoginResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /login` operation.
 */
export function handleLogin(
  response?: HandleLoginResponse | HttpResponseResolver<never, LoginData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, LoginData['body']>(
    `${options?.baseUrl ?? '*'}/login`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetProfileResponse = {
  body: GetProfileResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /whoami` operation.
 */
export function handleGetProfile(
  response?: HandleGetProfileResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/whoami`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListUsersResponse = {
  body: ListUsersResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /user` operation.
 */
export function handleListUsers(
  response?: HandleListUsersResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/user`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateUserResponse = {
  body: CreateUserResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /user` operation.
 */
export function handleCreateUser(
  response?: HandleCreateUserResponse | HttpResponseResolver<never, CreateUserData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateUserData['body']>(
    `${options?.baseUrl ?? '*'}/user`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleDeleteUserResponse = {
  body: DeleteUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /user/{id}` operation.
 */
export function handleDeleteUser(
  response?:
    | HandleDeleteUserResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/user/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetUserResponse = {
  body: GetUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /user/{id}` operation.
 */
export function handleGetUser(
  response?:
    | HandleGetUserResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/user/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleUpdateUserResponse = {
  body: UpdateUserResponses[200];
  status?: 200;
};

/**
 * Handler for the `PATCH /user/{id}` operation.
 */
export function handleUpdateUser(
  response?:
    | HandleUpdateUserResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        UpdateUserData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.patch<
    {
      id: string;
    },
    UpdateUserData['body']
  >(
    `${options?.baseUrl ?? '*'}/user/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListJoinedChatRoomsResponse = {
  body: ListJoinedChatRoomsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /chat` operation.
 */
export function handleListJoinedChatRooms(
  response?: HandleListJoinedChatRoomsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/chat`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetGlobalChatRoomResponse = {
  body: GetGlobalChatRoomResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /chat/room` operation.
 */
export function handleGetGlobalChatRoom(
  response?: HandleGetGlobalChatRoomResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/chat/room`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateChatRoomResponse = {
  body: CreateChatRoomResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /chat/room` operation.
 */
export function handleCreateChatRoom(
  response?: HandleCreateChatRoomResponse | HttpResponseResolver<never, CreateChatRoomData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateChatRoomData['body']>(
    `${options?.baseUrl ?? '*'}/chat/room`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetChatRoomResponse = {
  body: GetChatRoomResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /chat/room/{id}` operation.
 */
export function handleGetChatRoom(
  response?:
    | HandleGetChatRoomResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/chat/room/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleJobChatRoomResponse = {
  body: JobChatRoomResponses[200];
  status?: 200;
};

/**
 * Handler for the `POST /chat/room/{roomId}/join` operation.
 */
export function handleJobChatRoom(
  response?:
    | HandleJobChatRoomResponse
    | HttpResponseResolver<
        {
          roomId: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<
    {
      roomId: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/chat/room/:roomId/join`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleSendChatMessageResponse = {
  body: SendChatMessageResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /chat/room/{roomId}/msg` operation.
 */
export function handleSendChatMessage(
  response?:
    | HandleSendChatMessageResponse
    | HttpResponseResolver<
        {
          roomId: string;
        },
        SendChatMessageData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<
    {
      roomId: string;
    },
    SendChatMessageData['body']
  >(
    `${options?.baseUrl ?? '*'}/chat/room/:roomId/msg`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleUpdateChatMessageResponse = {
  body: UpdateChatMessageResponses[200];
  status?: 200;
};

/**
 * Handler for the `PUT /chat/room/{roomId}/msg/{msgId}` operation.
 */
export function handleUpdateChatMessage(
  response?:
    | HandleUpdateChatMessageResponse
    | HttpResponseResolver<
        {
          roomId: string;
          msgId: string;
        },
        UpdateChatMessageData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.put<
    {
      roomId: string;
      msgId: string;
    },
    UpdateChatMessageData['body']
  >(
    `${options?.baseUrl ?? '*'}/chat/room/:roomId/msg/:msgId`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListListingsResponse = {
  body: ListListingsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /marketplace` operation.
 */
export function handleListListings(
  response?: HandleListListingsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/marketplace`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateListingResponse = {
  body: CreateListingResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /marketplace` operation.
 */
export function handleCreateListing(
  response?: HandleCreateListingResponse | HttpResponseResolver<never, CreateListingData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateListingData['body']>(
    `${options?.baseUrl ?? '*'}/marketplace`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleDeleteListingResponse = {
  body: DeleteListingResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /marketplace/{id}` operation.
 */
export function handleDeleteListing(
  response?:
    | HandleDeleteListingResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/marketplace/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetListingResponse = {
  body: GetListingResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /marketplace/{id}` operation.
 */
export function handleGetListing(
  response?:
    | HandleGetListingResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/marketplace/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleUpdateListingResponse = {
  body: UpdateListingResponses[200];
  status?: 200;
};

/**
 * Handler for the `PATCH /marketplace/{id}` operation.
 */
export function handleUpdateListing(
  response?:
    | HandleUpdateListingResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        UpdateListingData['body']
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.patch<
    {
      id: string;
    },
    UpdateListingData['body']
  >(
    `${options?.baseUrl ?? '*'}/marketplace/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListCartItemsResponse = {
  body: ListCartItemsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /marketplace/cart/items` operation.
 */
export function handleListCartItems(
  response?: HandleListCartItemsResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/marketplace/cart/items`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleAddCartItemResponse = {
  body: AddCartItemResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /marketplace/cart/items` operation.
 */
export function handleAddCartItem(
  response?: HandleAddCartItemResponse | HttpResponseResolver<never, AddCartItemData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, AddCartItemData['body']>(
    `${options?.baseUrl ?? '*'}/marketplace/cart/items`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleRemoveCartItemResponse = {
  body: RemoveCartItemResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /marketplace/cart/items/{listingId}` operation.
 */
export function handleRemoveCartItem(
  response?:
    | HandleRemoveCartItemResponse
    | HttpResponseResolver<
        {
          listingId: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      listingId: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/marketplace/cart/items/:listingId`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetMoviesResponse = {
  body: GetMoviesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /movie` operation.
 */
export function handleGetMovies(
  response?: HandleGetMoviesResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/movie`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListMoviesResponse = {
  body: ListMoviesResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /movie/list` operation.
 */
export function handleListMovies(
  response?: HandleListMoviesResponse | HttpResponseResolver<never, never>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<never, never>(
    `${options?.baseUrl ?? '*'}/movie/list`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleGetMovieResponse = {
  body: GetMovieResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /movie/movie/{movieId}` operation.
 */
export function handleGetMovie(
  response?:
    | HandleGetMovieResponse
    | HttpResponseResolver<
        {
          movieId: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      movieId: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/movie/movie/:movieId`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleListMovieCommentsResponse = {
  body: ListMovieCommentsResponses[200];
  status?: 200;
};

/**
 * Handler for the `GET /movie/movie/{movieId}/comment` operation.
 */
export function handleListMovieComments(
  response?:
    | HandleListMovieCommentsResponse
    | HttpResponseResolver<
        {
          movieId: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.get<
    {
      movieId: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/movie/movie/:movieId/comment`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleCreateMovieCommentResponse = {
  body: CreateMovieCommentResponses[201];
  status?: 201;
};

/**
 * Handler for the `POST /movie/comment` operation.
 */
export function handleCreateMovieComment(
  response?:
    | HandleCreateMovieCommentResponse
    | HttpResponseResolver<never, CreateMovieCommentData['body']>,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.post<never, CreateMovieCommentData['body']>(
    `${options?.baseUrl ?? '*'}/movie/comment`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 201 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type HandleDeleteMovieCommentResponse = {
  body: DeleteMovieCommentResponses[200];
  status?: 200;
};

/**
 * Handler for the `DELETE /movie/comment/{id}` operation.
 */
export function handleDeleteMovieComment(
  response?:
    | HandleDeleteMovieCommentResponse
    | HttpResponseResolver<
        {
          id: string;
        },
        never
      >,
  options?: RequestHandlerOptions
): HttpHandler {
  return http.delete<
    {
      id: string;
    },
    never
  >(
    `${options?.baseUrl ?? '*'}/movie/comment/:id`,
    (info) => {
      if (typeof response === 'function') {
        return response(info);
      }
      const body = response?.body;
      if (body !== undefined) {
        return HttpResponse.json(body, { status: response?.status ?? 200 });
      }
      if (options?.responseFallback === 'passthrough') {
        return;
      }
      return new Response('Not Implemented', {
        status: 501,
        statusText: 'Not Implemented',
      });
    },
    options
  );
}

export type MswHandlerFactories = {
  /**
   * Handler for the `GET /product` operation.
   */
  getProducts: typeof handleGetProducts;
  /**
   * Handler for the `POST /product` operation.
   */
  createProduct: typeof handleCreateProduct;
  /**
   * Handler for the `GET /product/list` operation.
   */
  listProducts: typeof handleListProducts;
  /**
   * Handler for the `DELETE /product/{id}` operation.
   */
  deleteProduct: typeof handleDeleteProduct;
  /**
   * Handler for the `GET /product/{id}` operation.
   */
  getProduct: typeof handleGetProduct;
  /**
   * Handler for the `PUT /product/{id}` operation.
   */
  updateProduct: typeof handleUpdateProduct;
  /**
   * Handler for the `POST /product/comment/{id}` operation.
   */
  addProductComment: typeof handleAddProductComment;
  /**
   * Handler for the `GET /job` operation.
   */
  getJobs: typeof handleGetJobs;
  /**
   * Handler for the `POST /job` operation.
   */
  createJob: typeof handleCreateJob;
  /**
   * Handler for the `GET /job/list` operation.
   */
  listJobs: typeof handleListJobs;
  /**
   * Handler for the `DELETE /job/{id}` operation.
   */
  deleteJob: typeof handleDeleteJob;
  /**
   * Handler for the `GET /job/{id}` operation.
   */
  getJob: typeof handleGetJob;
  /**
   * Handler for the `PATCH /job/{id}` operation.
   */
  updateJob: typeof handleUpdateJob;
  /**
   * Handler for the `GET /job-application` operation.
   */
  listJobApplications: typeof handleListJobApplications;
  /**
   * Handler for the `POST /job-application` operation.
   */
  createJobApplication: typeof handleCreateJobApplication;
  /**
   * Handler for the `DELETE /job-application/{id}` operation.
   */
  deleteJobApplication: typeof handleDeleteJobApplication;
  /**
   * Handler for the `GET /marketing/type/{type}` operation.
   */
  getMarketingDataByType: typeof handleGetMarketingDataByType;
  /**
   * Handler for the `POST /marketing` operation.
   */
  createMarketingData: typeof handleCreateMarketingData;
  /**
   * Handler for the `DELETE /marketing/record/{id}` operation.
   */
  removeMarketingData: typeof handleRemoveMarketingData;
  /**
   * Handler for the `GET /marketing/record/{id}` operation.
   */
  getMarketingDataById: typeof handleGetMarketingDataById;
  /**
   * Handler for the `POST /file/upload` operation.
   */
  uploadFile: typeof handleUploadFile;
  /**
   * Handler for the `POST /register` operation.
   */
  register: typeof handleRegister;
  /**
   * Handler for the `POST /login` operation.
   */
  login: typeof handleLogin;
  /**
   * Handler for the `GET /whoami` operation.
   */
  getProfile: typeof handleGetProfile;
  /**
   * Handler for the `GET /user` operation.
   */
  listUsers: typeof handleListUsers;
  /**
   * Handler for the `POST /user` operation.
   */
  createUser: typeof handleCreateUser;
  /**
   * Handler for the `DELETE /user/{id}` operation.
   */
  deleteUser: typeof handleDeleteUser;
  /**
   * Handler for the `GET /user/{id}` operation.
   */
  getUser: typeof handleGetUser;
  /**
   * Handler for the `PATCH /user/{id}` operation.
   */
  updateUser: typeof handleUpdateUser;
  /**
   * Handler for the `GET /chat` operation.
   */
  listJoinedChatRooms: typeof handleListJoinedChatRooms;
  /**
   * Handler for the `GET /chat/room` operation.
   */
  getGlobalChatRoom: typeof handleGetGlobalChatRoom;
  /**
   * Handler for the `POST /chat/room` operation.
   */
  createChatRoom: typeof handleCreateChatRoom;
  /**
   * Handler for the `GET /chat/room/{id}` operation.
   */
  getChatRoom: typeof handleGetChatRoom;
  /**
   * Handler for the `POST /chat/room/{roomId}/join` operation.
   */
  jobChatRoom: typeof handleJobChatRoom;
  /**
   * Handler for the `POST /chat/room/{roomId}/msg` operation.
   */
  sendChatMessage: typeof handleSendChatMessage;
  /**
   * Handler for the `PUT /chat/room/{roomId}/msg/{msgId}` operation.
   */
  updateChatMessage: typeof handleUpdateChatMessage;
  /**
   * Handler for the `GET /marketplace` operation.
   */
  listListings: typeof handleListListings;
  /**
   * Handler for the `POST /marketplace` operation.
   */
  createListing: typeof handleCreateListing;
  /**
   * Handler for the `DELETE /marketplace/{id}` operation.
   */
  deleteListing: typeof handleDeleteListing;
  /**
   * Handler for the `GET /marketplace/{id}` operation.
   */
  getListing: typeof handleGetListing;
  /**
   * Handler for the `PATCH /marketplace/{id}` operation.
   */
  updateListing: typeof handleUpdateListing;
  /**
   * Handler for the `GET /marketplace/cart/items` operation.
   */
  listCartItems: typeof handleListCartItems;
  /**
   * Handler for the `POST /marketplace/cart/items` operation.
   */
  addCartItem: typeof handleAddCartItem;
  /**
   * Handler for the `DELETE /marketplace/cart/items/{listingId}` operation.
   */
  removeCartItem: typeof handleRemoveCartItem;
  /**
   * Handler for the `GET /movie` operation.
   */
  getMovies: typeof handleGetMovies;
  /**
   * Handler for the `GET /movie/list` operation.
   */
  listMovies: typeof handleListMovies;
  /**
   * Handler for the `GET /movie/movie/{movieId}` operation.
   */
  getMovie: typeof handleGetMovie;
  /**
   * Handler for the `GET /movie/movie/{movieId}/comment` operation.
   */
  listMovieComments: typeof handleListMovieComments;
  /**
   * Handler for the `POST /movie/comment` operation.
   */
  createMovieComment: typeof handleCreateMovieComment;
  /**
   * Handler for the `DELETE /movie/comment/{id}` operation.
   */
  deleteMovieComment: typeof handleDeleteMovieComment;
};

export type CreateMswHandlersResult = {
  all: (options?: {
    pick?: {
      [K in keyof MswHandlerFactories]?:
        | Parameters<MswHandlerFactories[K]>[0]
        | Parameters<MswHandlerFactories[K]>;
    };
  }) => ReadonlyArray<HttpHandler>;
  pick: MswHandlerFactories;
};

export function createMswHandlers(config: RequestHandlerOptions = {}): CreateMswHandlersResult {
  type Handler<R> = (response?: R, options?: RequestHandlerOptions) => HttpHandler;
  function wrap<R>(handler: Handler<R>): Handler<R> {
    return (response, options) => handler(response, { ...config, ...options });
  }
  const pick: CreateMswHandlersResult['pick'] = {
    getProducts: wrap(handleGetProducts),
    createProduct: wrap(handleCreateProduct),
    listProducts: wrap(handleListProducts),
    deleteProduct: wrap(handleDeleteProduct),
    getProduct: wrap(handleGetProduct),
    updateProduct: wrap(handleUpdateProduct),
    addProductComment: wrap(handleAddProductComment),
    getJobs: wrap(handleGetJobs),
    createJob: wrap(handleCreateJob),
    listJobs: wrap(handleListJobs),
    deleteJob: wrap(handleDeleteJob),
    getJob: wrap(handleGetJob),
    updateJob: wrap(handleUpdateJob),
    listJobApplications: wrap(handleListJobApplications),
    createJobApplication: wrap(handleCreateJobApplication),
    deleteJobApplication: wrap(handleDeleteJobApplication),
    getMarketingDataByType: wrap(handleGetMarketingDataByType),
    createMarketingData: wrap(handleCreateMarketingData),
    removeMarketingData: wrap(handleRemoveMarketingData),
    getMarketingDataById: wrap(handleGetMarketingDataById),
    uploadFile: wrap(handleUploadFile),
    register: wrap(handleRegister),
    login: wrap(handleLogin),
    getProfile: wrap(handleGetProfile),
    listUsers: wrap(handleListUsers),
    createUser: wrap(handleCreateUser),
    deleteUser: wrap(handleDeleteUser),
    getUser: wrap(handleGetUser),
    updateUser: wrap(handleUpdateUser),
    listJoinedChatRooms: wrap(handleListJoinedChatRooms),
    getGlobalChatRoom: wrap(handleGetGlobalChatRoom),
    createChatRoom: wrap(handleCreateChatRoom),
    getChatRoom: wrap(handleGetChatRoom),
    jobChatRoom: wrap(handleJobChatRoom),
    sendChatMessage: wrap(handleSendChatMessage),
    updateChatMessage: wrap(handleUpdateChatMessage),
    listListings: wrap(handleListListings),
    createListing: wrap(handleCreateListing),
    deleteListing: wrap(handleDeleteListing),
    getListing: wrap(handleGetListing),
    updateListing: wrap(handleUpdateListing),
    listCartItems: wrap(handleListCartItems),
    addCartItem: wrap(handleAddCartItem),
    removeCartItem: wrap(handleRemoveCartItem),
    getMovies: wrap(handleGetMovies),
    listMovies: wrap(handleListMovies),
    getMovie: wrap(handleGetMovie),
    listMovieComments: wrap(handleListMovieComments),
    createMovieComment: wrap(handleCreateMovieComment),
    deleteMovieComment: wrap(handleDeleteMovieComment),
  };
  const all: CreateMswHandlersResult['all'] = (options = {}) => {
    type OverrideValue<R> = R | [response?: R, options?: RequestHandlerOptions];
    function invoke<R>(fn: Handler<R>, override?: OverrideValue<R>): HttpHandler {
      return Array.isArray(override) ? fn(...override) : fn(override);
    }
    const overrides = options.pick ?? {};
    return [
      invoke(pick.updateChatMessage, overrides.updateChatMessage),
      invoke(pick.removeCartItem, overrides.removeCartItem),
      invoke(pick.jobChatRoom, overrides.jobChatRoom),
      invoke(pick.sendChatMessage, overrides.sendChatMessage),
      invoke(pick.listMovieComments, overrides.listMovieComments),
      invoke(pick.listCartItems, overrides.listCartItems),
      invoke(pick.addCartItem, overrides.addCartItem),
      invoke(pick.addProductComment, overrides.addProductComment),
      invoke(pick.getMarketingDataByType, overrides.getMarketingDataByType),
      invoke(pick.removeMarketingData, overrides.removeMarketingData),
      invoke(pick.getMarketingDataById, overrides.getMarketingDataById),
      invoke(pick.getChatRoom, overrides.getChatRoom),
      invoke(pick.getMovie, overrides.getMovie),
      invoke(pick.deleteMovieComment, overrides.deleteMovieComment),
      invoke(pick.listProducts, overrides.listProducts),
      invoke(pick.listJobs, overrides.listJobs),
      invoke(pick.uploadFile, overrides.uploadFile),
      invoke(pick.getGlobalChatRoom, overrides.getGlobalChatRoom),
      invoke(pick.createChatRoom, overrides.createChatRoom),
      invoke(pick.listMovies, overrides.listMovies),
      invoke(pick.createMovieComment, overrides.createMovieComment),
      invoke(pick.deleteProduct, overrides.deleteProduct),
      invoke(pick.getProduct, overrides.getProduct),
      invoke(pick.updateProduct, overrides.updateProduct),
      invoke(pick.deleteJob, overrides.deleteJob),
      invoke(pick.getJob, overrides.getJob),
      invoke(pick.updateJob, overrides.updateJob),
      invoke(pick.deleteJobApplication, overrides.deleteJobApplication),
      invoke(pick.deleteUser, overrides.deleteUser),
      invoke(pick.getUser, overrides.getUser),
      invoke(pick.updateUser, overrides.updateUser),
      invoke(pick.deleteListing, overrides.deleteListing),
      invoke(pick.getListing, overrides.getListing),
      invoke(pick.updateListing, overrides.updateListing),
      invoke(pick.getProducts, overrides.getProducts),
      invoke(pick.createProduct, overrides.createProduct),
      invoke(pick.getJobs, overrides.getJobs),
      invoke(pick.createJob, overrides.createJob),
      invoke(pick.listJobApplications, overrides.listJobApplications),
      invoke(pick.createJobApplication, overrides.createJobApplication),
      invoke(pick.createMarketingData, overrides.createMarketingData),
      invoke(pick.register, overrides.register),
      invoke(pick.login, overrides.login),
      invoke(pick.getProfile, overrides.getProfile),
      invoke(pick.listUsers, overrides.listUsers),
      invoke(pick.createUser, overrides.createUser),
      invoke(pick.listJoinedChatRooms, overrides.listJoinedChatRooms),
      invoke(pick.listListings, overrides.listListings),
      invoke(pick.createListing, overrides.createListing),
      invoke(pick.getMovies, overrides.getMovies),
    ];
  };
  return { all, pick };
}
