// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

export type ProductCommentDto = {
  userName: string;
  content: string;
  rating: number;
};

export type ProductResponse = {
  /**
   * Product name
   */
  name: string;
  descriptions: Array<string>;
  image: string;
  department: string;
  blurhash: string;
  /**
   * Unit price of the product
   */
  price: string;
  /**
   * _id of related products
   */
  related?: Array<string>;
  comments?: Array<ProductCommentDto>;
  /**
   * Unique id for the product
   */
  _id: string;
  __v: number;
  createdAt: string;
  updatedAt: string;
  images: {
    [key: string]: unknown;
  };
};

export type PaginatedDto = {
  docs: Array<{
    [key: string]: unknown;
  }>;
  totalDocs: number;
  limit: number;
  totalPages: number;
  page?: number;
  hasPrevPage: boolean;
  hasNextPage: boolean;
  prevPage?: number | null;
  nextPage?: number | null;
};

export type CreateProductDto = {
  /**
   * Product name
   */
  name: string;
  descriptions: Array<string>;
  image: string;
  department: string;
  blurhash: string;
  /**
   * Unit price of the product
   */
  price: string;
  /**
   * _id of related products
   */
  related?: Array<string>;
  comments?: Array<ProductCommentDto>;
  images: {
    [key: string]: unknown;
  };
};

export type ValidationErrorMessageDto = {
  /**
   * Object's property that hasn't passed validation
   */
  property: string;
  /**
   * Constraints that failed validation with error messages
   */
  constraints: {
    [key: string]: string;
  };
  /**
   * Contains all nested validation errors of the property
   */
  children?: Array<ValidationErrorMessageDto>;
};

export type ValidationErrorDto = {
  error: string;
  message: Array<ValidationErrorMessageDto>;
  statusCode: number;
};

export type UpdateProductDto = {
  /**
   * Product name
   */
  name?: string;
  descriptions?: Array<string>;
  image?: string;
  department?: string;
  blurhash?: string;
  /**
   * Unit price of the product
   */
  price?: string;
  /**
   * _id of related products
   */
  related?: Array<string>;
  comments?: Array<ProductCommentDto>;
  images?: {
    [key: string]: unknown;
  };
};

export type JobResponseDto = {
  /**
   * Title of the job
   */
  title: string;
  /**
   * Department the job is assigned to
   */
  department: string;
  level: 'internship' | 'entry' | 'experienced' | 'manager';
  summary: string;
  /**
   * Unique id for the job
   */
  _id: string;
  __v: number;
  createdAt: string;
  updatedAt: string;
  descriptions?: Array<string>;
  requirements?: Array<string>;
  headcount: number;
};

export type JobDto = {
  /**
   * Title of the job
   */
  title: string;
  /**
   * Department the job is assigned to
   */
  department: string;
  level: 'internship' | 'entry' | 'experienced' | 'manager';
  summary: string;
  descriptions?: Array<string>;
  requirements?: Array<string>;
  headcount: number;
};

export type UpdateJobDto = {
  /**
   * Title of the job
   */
  title?: string;
  /**
   * Department the job is assigned to
   */
  department?: string;
  level?: 'internship' | 'entry' | 'experienced' | 'manager';
  summary?: string;
  descriptions?: Array<string>;
  requirements?: Array<string>;
  headcount?: number;
};

export type JobApplicationDto = {
  linkedinUrl: string;
  job: JobResponseDto;
};

export type CreateJobApplicationDto = {
  linkedinUrl: string;
  jobId: string;
};

export type MarketingDataResponse = {
  /**
   * Type of the data
   */
  type: string;
  /**
   * Data
   */
  data: {
    [key: string]: unknown;
  };
  /**
   * Unique id for the data
   */
  _id: string;
};

export type MarketingDataDto = {
  /**
   * Type of the data
   */
  type: string;
  /**
   * Data
   */
  data: {
    [key: string]: unknown;
  };
};

export type UploadFileResponse = {
  /**
   * Public URL for the uploaded file
   */
  filePath: string;
};

export type RegisterDto = {
  name: string;
  email: string;
  password: string;
  avatar: string;
};

export type RegisterResponse = {
  name: string;
  email: string;
  avatar: string;
};

export type LoginDto = {
  /**
   * Email used during registration
   */
  username: string;
  password: string;
};

export type LoginResponse = {
  access_token: string;
};

export type UserProfile = {
  name: string;
  email: string;
  avatar: string;
  userId: string;
};

export type UserDto = {
  _id: string;
  name: string;
  /**
   * The email of the user. Must be unique.
   */
  email: string;
  avatar: string;
};

export type CreateUserDto = {
  name: string;
  /**
   * The email of the user. Must be unique.
   */
  email: string;
  avatar: string;
  password: string;
};

export type UpdateUserDto = {
  _id?: string;
  name?: string;
  /**
   * The email of the user. Must be unique.
   */
  email?: string;
  avatar?: string;
};

export type PickTypeClass = {
  roomType: 'global' | '1-to-1' | 'group';
  _id: string;
  updatedAt: string;
  createdAt: string;
};

export type ChatParticipantDto = {
  _id: string;
  name: string;
  avatar: string;
};

export type ChatMessageDto = {
  senderId: string;
  content: string;
};

export type ChatRoomResponseDto = {
  roomType: 'global' | '1-to-1' | 'group';
  participants: Array<ChatParticipantDto>;
  _id: string;
  __v: number;
  createdAt: string;
  updatedAt: string;
  participantUserIds: Array<string>;
  messages: Array<ChatMessageDto>;
};

export type ChatRoomDto = {
  roomType: 'global' | '1-to-1' | 'group';
  participantUserIds: Array<string>;
  messages: Array<ChatMessageDto>;
};

export type MessageDto = {
  content: string;
};

export type ChatMessageResponseDto = {
  senderId: string;
  content: string;
  _id: string;
  __v: number;
  createdAt: string;
  updatedAt: string;
};

export type MarketplaceListingResponse = {
  /**
   * Title for the listing
   */
  title: string;
  condition: 'new' | 'used_like-new' | 'used_good' | 'used_fair';
  /**
   * Description for the listing
   */
  description: string;
  availability: 'in-stock' | 'single-item';
  /**
   * Image for the listing
   */
  imageUrl?: string;
  /**
   * Num of available stock. Only applicable if availability is in-stock
   */
  numOfStock?: number;
  /**
   * Unique id for the listing
   */
  _id: string;
  __v: number;
  createdAt: string;
  updatedAt: string;
  price: number;
  category?: string;
};

export type MarketplaceListingDto = {
  /**
   * Title for the listing
   */
  title: string;
  condition: 'new' | 'used_like-new' | 'used_good' | 'used_fair';
  /**
   * Description for the listing
   */
  description: string;
  availability: 'in-stock' | 'single-item';
  /**
   * Image for the listing
   */
  imageUrl?: string;
  /**
   * Num of available stock. Only applicable if availability is in-stock
   */
  numOfStock?: number;
  price: number;
  category?: string;
};

export type UpdateMarketplaceListingDto = {
  /**
   * Title for the listing
   */
  title?: string;
  condition?: 'new' | 'used_like-new' | 'used_good' | 'used_fair';
  /**
   * Description for the listing
   */
  description?: string;
  availability?: 'in-stock' | 'single-item';
  /**
   * Image for the listing
   */
  imageUrl?: string;
  /**
   * Num of available stock. Only applicable if availability is in-stock
   */
  numOfStock?: number;
  price?: number;
  category?: string;
};

export type MarketplaceCartItemDto = {
  listing: MarketplaceListingDto;
  quantity: number;
};

export type AddMarketplaceCartItemDto = {
  listingId: string;
  quantity: number;
};

export type MovieDto = {
  _id: string;
  title: string;
  /**
   * Original title
   */
  originalTitle: string;
  releaseDate: string;
  /**
   * Overview
   */
  overview: string;
  posterUrl: string;
  backdropUrl: string;
  adult: boolean;
};

export type MovieCommentDto = {
  _id: string;
  /**
   * Rating
   */
  rating: number;
  userId: string;
  userName: string;
  movieId: string;
  content: string;
};

export type CreateMovieCommentDto = {
  /**
   * Rating
   */
  rating: number;
  movieId: string;
  content: string;
};

export type GetProductsData = {
  body?: never;
  path?: never;
  query?: {
    before?: string;
    limit?: number;
  };
  url: '/product';
};

export type GetProductsResponses = {
  200: Array<ProductResponse>;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type CreateProductData = {
  body: CreateProductDto;
  path?: never;
  query?: never;
  url: '/product';
};

export type CreateProductErrors = {
  400: ValidationErrorDto;
};

export type CreateProductError = CreateProductErrors[keyof CreateProductErrors];

export type CreateProductResponses = {
  201: ProductResponse;
};

export type CreateProductResponse = CreateProductResponses[keyof CreateProductResponses];

export type ListProductsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    name?: string;
    department?: string;
    /**
     * Search for products by name, department, or description
     */
    search?: string;
  };
  url: '/product/list';
};

export type ListProductsResponses = {
  200: PaginatedDto & {
    docs?: Array<ProductResponse>;
  };
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type DeleteProductData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/product/{id}';
};

export type DeleteProductErrors = {
  /**
   * No product found with the specified id
   */
  404: unknown;
};

export type DeleteProductResponses = {
  /**
   * Product is deleted successfully
   */
  200: ProductResponse;
};

export type DeleteProductResponse = DeleteProductResponses[keyof DeleteProductResponses];

export type GetProductData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/product/{id}';
};

export type GetProductResponses = {
  200: ProductResponse;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type UpdateProductData = {
  body: UpdateProductDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/product/{id}';
};

export type UpdateProductErrors = {
  400: ValidationErrorDto;
  /**
   * No product found with the specified id
   */
  404: unknown;
};

export type UpdateProductError = UpdateProductErrors[keyof UpdateProductErrors];

export type UpdateProductResponses = {
  200: ProductResponse;
};

export type UpdateProductResponse = UpdateProductResponses[keyof UpdateProductResponses];

export type AddProductCommentData = {
  body: ProductCommentDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/product/comment/{id}';
};

export type AddProductCommentErrors = {
  400: ValidationErrorDto;
  /**
   * No product found with the specified id
   */
  404: unknown;
};

export type AddProductCommentError = AddProductCommentErrors[keyof AddProductCommentErrors];

export type AddProductCommentResponses = {
  /**
   * Comment is added successfully
   */
  201: ProductResponse;
};

export type AddProductCommentResponse =
  AddProductCommentResponses[keyof AddProductCommentResponses];

export type GetJobsData = {
  body?: never;
  path?: never;
  query: {
    page?: number;
    limit?: number;
    delay: number;
  };
  url: '/job';
};

export type GetJobsResponses = {
  200: Array<JobResponseDto>;
};

export type GetJobsResponse = GetJobsResponses[keyof GetJobsResponses];

export type CreateJobData = {
  body: JobDto;
  path?: never;
  query?: never;
  url: '/job';
};

export type CreateJobErrors = {
  400: ValidationErrorDto;
};

export type CreateJobError = CreateJobErrors[keyof CreateJobErrors];

export type CreateJobResponses = {
  201: JobResponseDto;
};

export type CreateJobResponse = CreateJobResponses[keyof CreateJobResponses];

export type ListJobsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    title?: string;
    level?: 'internship' | 'entry' | 'experienced' | 'manager';
    /**
     * Search for jobs by title, level, department, summary, or description
     */
    search?: string;
  };
  url: '/job/list';
};

export type ListJobsResponses = {
  200: PaginatedDto & {
    docs?: Array<JobResponseDto>;
  };
};

export type ListJobsResponse = ListJobsResponses[keyof ListJobsResponses];

export type DeleteJobData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/job/{id}';
};

export type DeleteJobResponses = {
  200: JobResponseDto;
};

export type DeleteJobResponse = DeleteJobResponses[keyof DeleteJobResponses];

export type GetJobData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/job/{id}';
};

export type GetJobResponses = {
  200: JobResponseDto;
};

export type GetJobResponse = GetJobResponses[keyof GetJobResponses];

export type UpdateJobData = {
  body: UpdateJobDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/job/{id}';
};

export type UpdateJobErrors = {
  400: ValidationErrorDto;
};

export type UpdateJobError = UpdateJobErrors[keyof UpdateJobErrors];

export type UpdateJobResponses = {
  200: JobResponseDto;
};

export type UpdateJobResponse = UpdateJobResponses[keyof UpdateJobResponses];

export type ListJobApplicationsData = {
  body?: never;
  path?: never;
  query?: {
    jobId?: string;
  };
  url: '/job-application';
};

export type ListJobApplicationsErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type ListJobApplicationsResponses = {
  200: Array<JobApplicationDto>;
};

export type ListJobApplicationsResponse =
  ListJobApplicationsResponses[keyof ListJobApplicationsResponses];

export type CreateJobApplicationData = {
  body: CreateJobApplicationDto;
  path?: never;
  query?: never;
  url: '/job-application';
};

export type CreateJobApplicationErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type CreateJobApplicationResponses = {
  201: JobApplicationDto;
};

export type CreateJobApplicationResponse =
  CreateJobApplicationResponses[keyof CreateJobApplicationResponses];

export type DeleteJobApplicationData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/job-application/{id}';
};

export type DeleteJobApplicationErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type DeleteJobApplicationResponses = {
  200: JobApplicationDto;
};

export type DeleteJobApplicationResponse =
  DeleteJobApplicationResponses[keyof DeleteJobApplicationResponses];

export type GetMarketingDataByTypeData = {
  body?: never;
  path: {
    type: string;
  };
  query?: never;
  url: '/marketing/type/{type}';
};

export type GetMarketingDataByTypeResponses = {
  200: Array<MarketingDataResponse>;
};

export type GetMarketingDataByTypeResponse =
  GetMarketingDataByTypeResponses[keyof GetMarketingDataByTypeResponses];

export type CreateMarketingDataData = {
  body: MarketingDataDto;
  path?: never;
  query?: never;
  url: '/marketing';
};

export type CreateMarketingDataResponses = {
  201: MarketingDataResponse;
};

export type CreateMarketingDataResponse =
  CreateMarketingDataResponses[keyof CreateMarketingDataResponses];

export type RemoveMarketingDataData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/marketing/record/{id}';
};

export type RemoveMarketingDataErrors = {
  /**
   * No data with the specified id exists.
   */
  404: unknown;
};

export type RemoveMarketingDataResponses = {
  200: MarketingDataResponse;
};

export type RemoveMarketingDataResponse =
  RemoveMarketingDataResponses[keyof RemoveMarketingDataResponses];

export type GetMarketingDataByIdData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/marketing/record/{id}';
};

export type GetMarketingDataByIdErrors = {
  /**
   * No data with the specified id exists.
   */
  404: unknown;
};

export type GetMarketingDataByIdResponses = {
  200: MarketingDataResponse;
};

export type GetMarketingDataByIdResponse =
  GetMarketingDataByIdResponses[keyof GetMarketingDataByIdResponses];

export type UploadFileData = {
  body: {
    file?: Blob | File;
  };
  path?: never;
  query?: never;
  url: '/file/upload';
};

export type UploadFileResponses = {
  201: UploadFileResponse;
};

export type UploadFileResponse2 = UploadFileResponses[keyof UploadFileResponses];

export type RegisterData = {
  body: RegisterDto;
  path?: never;
  query?: never;
  url: '/register';
};

export type RegisterErrors = {
  /**
   * Email already used
   */
  409: unknown;
};

export type RegisterResponses = {
  201: RegisterResponse;
};

export type RegisterResponse2 = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
  body: LoginDto;
  path?: never;
  query?: never;
  url: '/login';
};

export type LoginErrors = {
  /**
   * Invalid credentials
   */
  401: unknown;
};

export type LoginResponses = {
  /**
   * Login success
   */
  200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type GetProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/whoami';
};

export type GetProfileErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type GetProfileResponses = {
  200: UserProfile;
};

export type GetProfileResponse = GetProfileResponses[keyof GetProfileResponses];

export type ListUsersData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    /**
     * Search for users by name or email
     */
    search?: string;
  };
  url: '/user';
};

export type ListUsersErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type ListUsersResponses = {
  200: PaginatedDto & {
    docs?: Array<UserDto>;
  };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type CreateUserData = {
  body: CreateUserDto;
  path?: never;
  query?: never;
  url: '/user';
};

export type CreateUserErrors = {
  400: ValidationErrorDto;
  /**
   * User is not authorized
   */
  401: unknown;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
  201: UserDto;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type DeleteUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/user/{id}';
};

export type DeleteUserErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type DeleteUserResponses = {
  200: UserDto;
};

export type DeleteUserResponse = DeleteUserResponses[keyof DeleteUserResponses];

export type GetUserData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/user/{id}';
};

export type GetUserErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type GetUserResponses = {
  200: UserDto;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
  body: UpdateUserDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/user/{id}';
};

export type UpdateUserErrors = {
  400: ValidationErrorDto;
  /**
   * User is not authorized
   */
  401: unknown;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
  200: UserDto;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListJoinedChatRoomsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/chat';
};

export type ListJoinedChatRoomsErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type ListJoinedChatRoomsResponses = {
  200: Array<PickTypeClass>;
};

export type ListJoinedChatRoomsResponse =
  ListJoinedChatRoomsResponses[keyof ListJoinedChatRoomsResponses];

export type GetGlobalChatRoomData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/chat/room';
};

export type GetGlobalChatRoomResponses = {
  200: ChatRoomResponseDto;
};

export type GetGlobalChatRoomResponse =
  GetGlobalChatRoomResponses[keyof GetGlobalChatRoomResponses];

export type CreateChatRoomData = {
  body: ChatRoomDto;
  path?: never;
  query?: never;
  url: '/chat/room';
};

export type CreateChatRoomErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type CreateChatRoomResponses = {
  201: ChatRoomResponseDto;
};

export type CreateChatRoomResponse = CreateChatRoomResponses[keyof CreateChatRoomResponses];

export type GetChatRoomData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/chat/room/{id}';
};

export type GetChatRoomResponses = {
  200: ChatRoomResponseDto;
};

export type GetChatRoomResponse = GetChatRoomResponses[keyof GetChatRoomResponses];

export type JobChatRoomData = {
  body?: never;
  path: {
    roomId: string;
  };
  query?: never;
  url: '/chat/room/{roomId}/join';
};

export type JobChatRoomErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type JobChatRoomResponses = {
  200: ChatRoomResponseDto;
};

export type JobChatRoomResponse = JobChatRoomResponses[keyof JobChatRoomResponses];

export type SendChatMessageData = {
  body: MessageDto;
  path: {
    roomId: string;
  };
  query?: never;
  url: '/chat/room/{roomId}/msg';
};

export type SendChatMessageErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type SendChatMessageResponses = {
  201: ChatMessageResponseDto;
};

export type SendChatMessageResponse = SendChatMessageResponses[keyof SendChatMessageResponses];

export type UpdateChatMessageData = {
  body: MessageDto;
  path: {
    roomId: string;
    msgId: string;
  };
  query?: never;
  url: '/chat/room/{roomId}/msg/{msgId}';
};

export type UpdateChatMessageErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type UpdateChatMessageResponses = {
  200: ChatMessageResponseDto;
};

export type UpdateChatMessageResponse =
  UpdateChatMessageResponses[keyof UpdateChatMessageResponses];

export type ListListingsData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/marketplace';
};

export type ListListingsResponses = {
  200: Array<MarketplaceListingResponse>;
};

export type ListListingsResponse = ListListingsResponses[keyof ListListingsResponses];

export type CreateListingData = {
  body: MarketplaceListingDto;
  path?: never;
  query?: never;
  url: '/marketplace';
};

export type CreateListingResponses = {
  201: MarketplaceListingResponse;
};

export type CreateListingResponse = CreateListingResponses[keyof CreateListingResponses];

export type DeleteListingData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/marketplace/{id}';
};

export type DeleteListingResponses = {
  200: MarketplaceListingResponse;
};

export type DeleteListingResponse = DeleteListingResponses[keyof DeleteListingResponses];

export type GetListingData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/marketplace/{id}';
};

export type GetListingResponses = {
  200: MarketplaceListingResponse;
};

export type GetListingResponse = GetListingResponses[keyof GetListingResponses];

export type UpdateListingData = {
  body: UpdateMarketplaceListingDto;
  path: {
    id: string;
  };
  query?: never;
  url: '/marketplace/{id}';
};

export type UpdateListingResponses = {
  200: MarketplaceListingResponse;
};

export type UpdateListingResponse = UpdateListingResponses[keyof UpdateListingResponses];

export type ListCartItemsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/marketplace/cart/items';
};

export type ListCartItemsErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type ListCartItemsResponses = {
  200: Array<MarketplaceCartItemDto>;
};

export type ListCartItemsResponse = ListCartItemsResponses[keyof ListCartItemsResponses];

export type AddCartItemData = {
  body: AddMarketplaceCartItemDto;
  path?: never;
  query?: never;
  url: '/marketplace/cart/items';
};

export type AddCartItemErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type AddCartItemResponses = {
  201: {
    [key: string]: unknown;
  };
};

export type AddCartItemResponse = AddCartItemResponses[keyof AddCartItemResponses];

export type RemoveCartItemData = {
  body?: never;
  path: {
    listingId: string;
  };
  query?: never;
  url: '/marketplace/cart/items/{listingId}';
};

export type RemoveCartItemErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type RemoveCartItemResponses = {
  200: {
    [key: string]: unknown;
  };
};

export type RemoveCartItemResponse = RemoveCartItemResponses[keyof RemoveCartItemResponses];

export type GetMoviesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
  };
  url: '/movie';
};

export type GetMoviesResponses = {
  200: Array<MovieDto>;
};

export type GetMoviesResponse = GetMoviesResponses[keyof GetMoviesResponses];

export type ListMoviesData = {
  body?: never;
  path?: never;
  query?: {
    page?: number;
    limit?: number;
    /**
     * Search for movies by title or description
     */
    search?: string;
  };
  url: '/movie/list';
};

export type ListMoviesResponses = {
  200: PaginatedDto & {
    docs?: Array<MovieDto>;
  };
};

export type ListMoviesResponse = ListMoviesResponses[keyof ListMoviesResponses];

export type GetMovieData = {
  body?: never;
  path: {
    movieId: string;
  };
  query?: never;
  url: '/movie/movie/{movieId}';
};

export type GetMovieResponses = {
  200: MovieDto;
};

export type GetMovieResponse = GetMovieResponses[keyof GetMovieResponses];

export type ListMovieCommentsData = {
  body?: never;
  path: {
    movieId: string;
  };
  query?: never;
  url: '/movie/movie/{movieId}/comment';
};

export type ListMovieCommentsResponses = {
  200: Array<MovieCommentDto>;
};

export type ListMovieCommentsResponse =
  ListMovieCommentsResponses[keyof ListMovieCommentsResponses];

export type CreateMovieCommentData = {
  body: CreateMovieCommentDto;
  path?: never;
  query?: never;
  url: '/movie/comment';
};

export type CreateMovieCommentErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type CreateMovieCommentResponses = {
  201: MovieCommentDto;
};

export type CreateMovieCommentResponse =
  CreateMovieCommentResponses[keyof CreateMovieCommentResponses];

export type DeleteMovieCommentData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: '/movie/comment/{id}';
};

export type DeleteMovieCommentErrors = {
  /**
   * User is not authorized
   */
  401: unknown;
};

export type DeleteMovieCommentResponses = {
  200: MovieCommentDto;
};

export type DeleteMovieCommentResponse =
  DeleteMovieCommentResponses[keyof DeleteMovieCommentResponses];
