name: Build Site and Deploy
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '5 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          PUBLIC_WEBPUSH_KEY: ${{ secrets.PUBLIC_WEBPUSH_KEY }}
          PUBLIC_API_BASE_URL: ${{ secrets.PUBLIC_API_BASE_URL }}
          CI: true

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        id: netlify-deploy
        with:
          publish-dir: './apps/v2/dist'
          netlify-config-path: ./netlify.toml
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Test
        run: pnpm -r run test:coverage
        env:
          CI: true
