name: Build Site
on:
  push:
    branches:
      - master
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Cache Cypress
        uses: actions/cache@v1
        with:
          path: '~/.cache/Cypress'
          key: cacheCypressBinary-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            cacheCypressBinary-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Install Cypress dependencies
        run: sudo apt-get install -yq libgtk2.0-0 libgtk-3-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

      - name: Build
        run: yarn build
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GATSBY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GATSBY_DISCUQ_NAME: malcolmkee
          YOUTUBE_API_ID: ${{ secrets.YOUTUBE_API_ID }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
