name: Build Site and Deploy
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true
          GATSBY_DISCUQ_NAME: malcolmkee
          YOUTUBE_API_ID: ${{ secrets.YOUTUBE_API_ID }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}

      - name: Migration Report
        run: yarn report

      - name: Commit Migration Report if Changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply migration report changes

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        id: netlify-deploy
        with:
          publish-dir: './public'
          netlify-config-path: ./netlify.toml
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      # - name: Check Deploy Output
      #   run: echo ${{ steps.netlify-deploy.outputs.deploy-url }}

      # - name: Run E2E Test
      #   uses: cypress-io/github-action@v5
      #   with:
      #     config: baseUrl=${{ steps.netlify-deploy.outputs.deploy-url }}/archive
      #     project: ./e2e
