name: Trigger Build
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]

jobs:
  build:
    name: Trigger Build
    runs-on: ubuntu-latest
    steps:
      - name: Call Travis API
        env: # Or as an environment variable
          TRAVIS_API_KEY: ${{ secrets.TRAVIS_API_KEY }}
        run: |
          body='{
          "request": {
          "branch": "master"
          }}'

          curl -s -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -H "Travis-API-Version: 3" \
            -H "Authorization: token $TRAVIS_API_KEY" \
            -d "$body" \
            https://api.travis-ci.com/repo/malcolm-kee%2Fmalcolm-kee/requests
